<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AiSummarizer.Application\AiSummarizer.Application.csproj" />
    <ProjectReference Include="..\AiSummarizer.Domain\AiSummarizer.Domain.csproj" />
    <ProjectReference Include="..\AiSummarizer.Infrastructure\AiSummarizer.Infrastructure.csproj" />
    <ProjectReference Include="..\AiSummarizer.Shared\AiSummarizer.Shared.csproj" />
  </ItemGroup>
</Project>
